language: go

go:
  - 1.11.x
  - 1.12.x
  - tip

before_install:
  - go get -u github.com/codegangsta/negroni
  - go get -u honnef.co/go/tools/cmd/staticcheck

script:
  - staticcheck
  - go test -v -race -tags=integration
